steps = [{"id"=>6,
 "kit_id"=>2,
 "description"=>"For your tic-tac-toe game, you'll need to create boxes where someone can click to play their turn. Let's create the first box!",
 "spec"=>"-> $(\"svg rect\").length > 0",
 "success_message"=>"Wonderful, you made the first box!",
 "position"=>2,
 "created_at"=>"2012-01-02 23:58:19 UTC",
 "updated_at"=>"2012-02-29 22:23:18 UTC",
 "title"=>nil,
 "hint"=>nil,
 "solution"=>nil,
 "image_url"=>nil,
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>7,
 "kit_id"=>2,
 "description"=>"This is great. Now we need 9 boxes. See if you can create them in a clever way. ",
 "spec"=>"-> $(\"svg rect\").length == 9",
 "success_message"=>"woohoo! 9 rectangles. wowza",
 "position"=>3,
 "created_at"=>"2012-01-03 23:58:18 UTC",
 "updated_at"=>"2012-01-03 23:58:18 UTC",
 "title"=>nil,
 "hint"=>nil,
 "solution"=>nil,
 "image_url"=>nil,
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>8,
 "kit_id"=>2,
 "description"=>"Now make sure they are not on top of each other. ",
 "spec"=>"->\r\n  x_attrs =  _.map($(\"svg rect\"), (i) ->  $(i).attr(\"x\") )\r\n  y_attrs = _.map($(\"svg rect\"), (i) ->  $(i).attr(\"y\") )\r\n  heights = _.map($(\"svg rect\"), (i) ->  $(i).attr(\"height\") )\r\n  widths = _.map($(\"svg rect\"), (i) ->  $(i).attr(\"width\") )\r\n \r\n  sortedX = _.sortBy(x_attrs, (i) -> i)\r\n  sortedY = _.sortBy(y_attrs, (i) -> i)\r\n\r\n  if _.isEqual(_.uniq(sortedX), [\"0\",  \"100\",  \"200\"]) && _.isEqual(sortedY, sortedX)\r\n    _.isEqual(_.uniq(heights), [\"100\"]) && _.isEqual(_.uniq(widths), [\"100\"])",
 "success_message"=>"Woohoo, all the rectangles are in the right spot!",
 "position"=>4,
 "created_at"=>"2012-01-04 04:07:51 UTC",
 "updated_at"=>"2012-01-04 04:26:35 UTC",
 "title"=>nil,
 "hint"=>nil,
 "solution"=>nil,
 "image_url"=>nil,
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>16,
 "kit_id"=>3,
 "description"=>"Our puppy needs eyes. Let's make a white ellipse for the eye with a black circle in the middle for the pupil. \r\n\r\nHere is the code to get you started with the left eye, you'll have to add the fill yourself.  \r\n<code>leftEyeOuter = paper.ellipse(175, 175, 12,15)\r\nleftEye = paper.circle(175, 170, 7)</code>\r\n\r\nRemember that the first number controls the horizontal position.",
 "spec"=>"assert( (-> \r\n  eyes = 0\r\n  pupils = $frame.find(\"svg circle\").length\r\n  _.each($frame.find(\"svg ellipse\"), (ellipse)-> \r\n    if $(ellipse).attr(\"fill\").match(/#/i)\r\n      eyes += 1\r\n  )\r\n  if (eyes >= 5 && pupils == 2) || (pupils == 0 && eyes >= 7)\r\n    return true\r\n  else\r\n    return false\r\n), \"Make 2 eyes with pupils\")",
 "success_message"=>"Hopefully that additional practice using ellipse and circle have made you an expert. There's just one more thing to add and then you can let your creativity flow. ",
 "position"=>8,
 "created_at"=>"2012-01-06 16:15:57 UTC",
 "updated_at"=>"2012-04-23 19:14:24 UTC",
 "title"=>"Puppy eyes",
 "hint"=>"Add fill in the same way you did for the ears.\r\n\r\n<code><add>leftEyeOuter.attr('fill', 'white')\r\nleftEye.attr('fill', 'black')</add></code>",
 "solution"=>"paper = makeWorkspace()\r\n\r\nleftEar=paper.ellipse(150,215,40,80)\r\nleftEar.attr(\"fill\", \"saddleBrown\")\r\nrightEar=paper.ellipse(250,215,40,80)\r\nrightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\nleftEar.rotate(\"20\")\r\nrightEar.rotate(\"340\")\r\n\r\n\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")\r\n\r\n\r\nleftEyeOuter = paper.ellipse(175, 175, 12,15).attr(\"fill\", \"white\")\r\nleftEye = paper.circle(175, 170, 7).attr(\"fill\", \"black\")\r\nrightEyeOuter = paper.ellipse(225, 175, 12,15).attr(\"fill\", \"white\")\r\nrightEye = paper.circle(225, 170, 7).attr(\"fill\", \"black\")",
 "image_url"=>"step7.png",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>9,
 "kit_id"=>3,
 "description"=>"Before we can draw a puppy, we need something to draw it on.  Type this: \r\n\r\n<code><num>1</num><add>makeWorkspace()</add> </code>\r\n\r\ninto the code editor below, then hit \"Run This\".\r\n",
 "spec"=>"assert(( -> $frame.find(\"svg\").length > 0), \"add the paper to the page\")",
 "success_message"=>"You just made an HTML canvas. That's the latest fancy thing your browser can do- using a canvas lets you draw on a website!",
 "position"=>1,
 "created_at"=>"2012-01-05 22:15:35 UTC",
 "updated_at"=>"2012-04-23 16:10:16 UTC",
 "title"=>"The drawing board",
 "hint"=>"Make sure you copied it exactly, the code is case sensitive (\"case sensitive\" means it matters whether it is upper case or lower case).",
 "solution"=>"makeWorkspace()",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>5,
 "kit_id"=>2,
 "description"=>"da",
 "spec"=>"-> $(\"svg\").length > 0",
 "success_message"=>"",
 "position"=>1,
 "created_at"=>"2012-01-02 23:58:19 UTC",
 "updated_at"=>"2012-03-20 14:15:34 UTC",
 "title"=>"Let's start at the very beginning, a very good place to start.",
 "hint"=>"",
 "solution"=>"",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>"ads"},
{"id"=>17,
 "kit_id"=>3,
 "description"=>"The last thing we need is a nose. \r\n\r\nLet's make a black, oblong oval at the end of the face. \r\n\r\nHighlight the numbers and use the up and down arrows to move the nose around the page and change its size and shape. ",
 "spec"=>"assert( (-> \r\n  nose = false\r\n  _.each($frame.find(\"svg ellipse\"), (ellipse)-> \r\n    if parseInt($(ellipse).attr(\"rx\"), 10) > parseInt($(ellipse).attr(\"ry\"), 10)\r\n      nose = true\r\n  )\r\n  return nose\r\n), \"The nose should be wider than it is long\")\r\n\r\n\r\nassert( (-> \r\n  nose = false\r\n  _.each($frame.find(\"svg ellipse\"), (ellipse)-> \r\n    if parseInt($(ellipse).attr(\"rx\"),10) > parseInt($(ellipse).attr(\"ry\"), 10) \r\n      x = parseInt($(ellipse).attr(\"cx\"), 10)\r\n      if x >= 180 && x <= 220\r\n        nose = true\r\n  )\r\n  return nose\r\n), \"The nose should be more centered\")\r\n\r\nassert( (-> \r\n  nose = false\r\n  _.each($frame.find(\"svg ellipse\"), (ellipse)-> \r\n    if parseInt($(ellipse).attr(\"rx\"),10) > parseInt($(ellipse).attr(\"ry\"), 10) \r\n      y = parseInt($(ellipse).attr(\"cy\"), 10)\r\n      if y <= 280\r\n        nose = true\r\n  )\r\n  return nose\r\n), \"The nose should be farther up\")\r\n\r\nassert( (-> \r\n  nose = false\r\n  _.each($frame.find(\"svg ellipse\"), (ellipse)-> \r\n    y = parseInt($(ellipse).attr(\"cy\"), 10)\r\n    if y >= 270\r\n      nose = true\r\n  )\r\n  return nose\r\n), \"The nose should be farther down\")\r\n\r\nassert( (-> \r\n  nose = false\r\n  _.each($frame.find(\"svg ellipse\"), (ellipse)-> \r\n    if parseInt($(ellipse).attr(\"rx\"),10) > parseInt($(ellipse).attr(\"ry\"), 10) \r\n      if $(ellipse).attr(\"fill\").match(/#/i)\r\n        nose = true\r\n  )\r\n  return nose\r\n), \"Give the nose a color.\")",
 "success_message"=>"Your puppy is complete- now click Next to see your very own website with for your puppy. You can give her a name, share with your friends and even come back and keep coding to make your puppy even better. ",
 "position"=>9,
 "created_at"=>"2012-01-06 16:19:59 UTC",
 "updated_at"=>"2012-04-23 19:16:33 UTC",
 "title"=>"The nose knows",
 "hint"=>"Try making the width (3rd parameter) bigger than the height (4th parameter). ",
 "solution"=>"paper = makeWorkspace()\r\n\r\nleftEar=paper.ellipse(150,215,40,80)\r\nleftEar.attr(\"fill\", \"saddleBrown\")\r\nrightEar=paper.ellipse(250,215,40,80)\r\nrightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\nleftEar.rotate(\"20\")\r\nrightEar.rotate(\"340\")\r\n\r\n\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")\r\n\r\n\r\nleftEyeOuter = paper.ellipse(175, 175, 12,15).attr(\"fill\", \"white\")\r\nleftEye = paper.circle(175, 170, 7).attr(\"fill\", \"black\")\r\nrightEyeOuter = paper.ellipse(225, 175, 12,15).attr(\"fill\", \"white\")\r\nrightEye = paper.circle(225, 170, 7).attr(\"fill\", \"black\")\r\n\r\nnose = paper.ellipse(200, 273, 25,10).attr(\"fill\", \"black\")\r\n",
 "image_url"=>"step8.png",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>18,
 "kit_id"=>4,
 "description"=>"Now we need to make our dog a nice shade of brown. We want to set the oval's \"fill\" attribute to \"saddlebrown\". We change attributes of the ellipse with the \"attr\" method.\r\n\r\n<code>face.attr(\"fill\", \"saddlebrown\")</code>\r\n\r\nyou will want to assign the \"face\" variable to your ellipse so that you can call attr.",
 "spec"=>"assert((->$(\"svg ellipse\").attr(\"fill\").match(/#8B4513/i)), \"Uh oh, the puppy isn\"t the right brown :(\")",
 "success_message"=>"Look at that vicious dawg! ",
 "position"=>3,
 "created_at"=>"2012-01-06 00:39:08 UTC",
 "updated_at"=>"2012-02-29 22:23:18 UTC",
 "title"=>"Adding Some Color",
 "hint"=>"Try typing in the code block and make sure you've assigned face to the ellipse. ",
 "solution"=>"paper = makeWorkspace()\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")",
 "image_url"=>nil,
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>19,
 "kit_id"=>4,
 "description"=>"Our puppy needs ears. Let's make 2 ellipses on the side of the head. See if you can put the ears behind the head. ",
 "spec"=>"assert( (-> ($(\"svg ellipse\").length == 3)), \"You need 2 ears. No more, no less.\")",
 "success_message"=>"Woof! You hear that? your dog did. ",
 "position"=>4,
 "created_at"=>"2012-01-06 00:48:29 UTC",
 "updated_at"=>"2012-01-06 00:54:32 UTC",
 "title"=>"Do your ears hang low?",
 "hint"=>"Try making ellipses just a little smaller than the head and offset on the center coordinate (that's the first argument). ",
 "solution"=>"paper = makeWorkspace()\r\n\r\nleftEar=paper.ellipse(150,215,40,80)\r\nleftEar.attr(\"fill\", \"saddleBrown\")\r\nrightEar=paper.ellipse(250,215,40,80)\r\nrightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")",
 "image_url"=>nil,
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>20,
 "kit_id"=>4,
 "description"=>"First, let's make the ears brown, the same shade as the face. Do you remember how to do this? \r\n\r\nMake sure the ears are *behind* the head, we don't want the backs of the ears sticking over the face. Try experimenting with moving the code around, maybe if you make the ears before the face they will be float behind it. ",
 "spec"=>"",
 "success_message"=>"Brown ears! Awesome!",
 "position"=>5,
 "created_at"=>"2012-01-06 15:41:50 UTC",
 "updated_at"=>"2012-01-06 16:12:46 UTC",
 "title"=>"Jazz up the ears",
 "hint"=>"Try using the .attr(\"fill\", \"saddlebrown\") method on each of the ears. ",
 "solution"=>"paper = makeWorkspace()\r\n\r\nleftEar=paper.ellipse(150,215,40,80)\r\nleftEar.attr(\"fill\", \"saddleBrown\")\r\nrightEar=paper.ellipse(250,215,40,80)\r\nrightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")\r\n",
 "image_url"=>nil,
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>14,
 "kit_id"=>3,
 "description"=>"Let's make the ears brown, the same shade as the face. Here's the  code for the right ear, you can try the left ear on your own.\r\n<code><add>rightEar.attr('fill', 'saddlebrown')</add></code>\r\n\r\nMake sure the ears are *behind* the head, we don't want the backs of the ears sticking over the face.  Try experimenting by moving the lines of code into a different order to make this work.     ",
 "spec"=>"assert( (-> \r\n  brownEllipses = 0\r\n  _.each($frame.find(\"svg ellipse\"), (ellipse)-> \r\n    if $(ellipse).attr(\"fill\").match(/#/i) \r\n      brownEllipses += 1\r\n  )\r\n  if brownEllipses < 3\r\n    return false\r\n  else\r\n    return true\r\n), \"Make both ears saddle brown in color\")",
 "success_message"=>"You have set the \"fill\" attribute of each ear. Before they were clear, now they are colored in! Try customizing your puppy with different colors by highlighting the color name inside the quotes and using the up and down arrows.",
 "position"=>6,
 "created_at"=>"2012-01-06 15:41:50 UTC",
 "updated_at"=>"2012-04-23 19:06:24 UTC",
 "title"=>"Jazz up the ears",
 "hint"=>"The computer reads the code you've written from the top down, so to move the ears behind the head, you need to draw them first, before the face.  \r\n\r\nCut and paste the lines of code for \"rightEar\" and \"leftEar\" and move them above the code for \"face\".  ",
 "solution"=>"paper = makeWorkspace()\r\n\r\nleftEar=paper.ellipse(150,215,40,80)\r\nleftEar.attr(\"fill\", \"saddleBrown\")\r\nrightEar=paper.ellipse(250,215,40,80)\r\nrightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")\r\n",
 "image_url"=>"step5.png",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>22,
 "kit_id"=>4,
 "description"=>"Our puppy needs eyes. Let's make a white ellipse for the eye with a black circle in the middle for the pupil. Try to make it look like the picture. \r\n\r\nYou can make a circle either by creating an ellipse with equal width and height or calling the circle method that only takes a radius. ",
 "spec"=>"",
 "success_message"=>"I'm lookin' at you! ",
 "position"=>7,
 "created_at"=>"2012-01-06 16:15:57 UTC",
 "updated_at"=>"2012-01-06 16:15:57 UTC",
 "title"=>"Puppy eyes",
 "hint"=>"Try this for the left eye, see if you can mirror it on the right. \r\n\r\n\r\nleftEyeOuter = paper.ellipse(175, 175, 12,15)\r\nleftEye = paper.circle(175, 170, 7)",
 "solution"=>"paper = makeWorkspace()\r\n\r\nleftEar=paper.ellipse(150,215,40,80)\r\nleftEar.attr(\"fill\", \"saddleBrown\")\r\nrightEar=paper.ellipse(250,215,40,80)\r\nrightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\nleftEar.transform(\"R20\")\r\nrightEar.transform(\"R-20\")\r\n\r\n\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")\r\n\r\n\r\nleftEyeOuter = paper.ellipse(175, 175, 12,15).attr(\"fill\", \"white\")\r\nleftEye = paper.circle(175, 170, 7).attr(\"fill\", \"black\")\r\nrightEyeOuter = paper.ellipse(225, 175, 12,15).attr(\"fill\", \"white\")\r\nrightEye = paper.circle(225, 170, 7).attr(\"fill\", \"black\")",
 "image_url"=>nil,
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>23,
 "kit_id"=>4,
 "description"=>"The last thing we need is a nose. \r\n\r\nLet's make a black, oblong oval at the end of the face. ",
 "spec"=>"assert((->true), \"hi\")",
 "success_message"=>"Woohoo! You made a puppy face!! ",
 "position"=>8,
 "created_at"=>"2012-01-06 16:19:59 UTC",
 "updated_at"=>"2012-01-12 17:27:48 UTC",
 "title"=>"The nose knows",
 "hint"=>"Try making the width (3rd parameter) bigger than the height (1st parameter). ",
 "solution"=>"paper = makeWorkspace()\r\n\r\nleftEar=paper.ellipse(150,215,40,80)\r\nleftEar.attr(\"fill\", \"saddleBrown\")\r\nrightEar=paper.ellipse(250,215,40,80)\r\nrightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\nleftEar.transform(\"R20\")\r\nrightEar.transform(\"R-20\")\r\n\r\n\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")\r\n\r\n\r\nleftEyeOuter = paper.ellipse(175, 175, 12,15).attr(\"fill\", \"white\")\r\nleftEye = paper.circle(175, 170, 7).attr(\"fill\", \"black\")\r\nrightEyeOuter = paper.ellipse(225, 175, 12,15).attr(\"fill\", \"white\")\r\nrightEye = paper.circle(225, 170, 7).attr(\"fill\", \"black\")\r\n\r\nnose = paper.ellipse(200, 273, 25,10).attr(\"fill\", \"black\")\r\n",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>24,
 "kit_id"=>4,
 "description"=>"Before we can draw a puppy, we need a piece of paper. To get your paper, type this: \r\n\r\n<code>makeWorkspace() </code>\r\n\r\ninto the editor",
 "spec"=>"assert(( -> $(\"svg\").length > 0), \"There\"s no paper on the page!\")",
 "success_message"=>"Woohoo! Now you're ready to start drawing.",
 "position"=>1,
 "created_at"=>"2012-01-05 22:15:35 UTC",
 "updated_at"=>"2012-02-29 22:23:18 UTC",
 "title"=>"The drawing board",
 "hint"=>"Make sure you copied it exactly, the code is case sensitive (\"case sensitive\" means it matters whether it is upper case or lower case).",
 "solution"=>"makeWorkspace()",
 "image_url"=>nil,
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>26,
 "kit_id"=>5,
 "description"=>"We're going to start with the puppy from the previous kit. \r\n\r\nLet's save time and copy our code from last time: \r\n<code>\r\n\r\npaper = makeWorkspace()\r\n\r\n  leftEar=paper.ellipse(150,215,40,80)\r\n  leftEar.attr(\"fill\", \"saddleBrown\")\r\n  rightEar=paper.ellipse(250,215,40,80)\r\n  rightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\n  leftEar.transform(\"R20\")\r\n  rightEar.transform(\"R-20\")\r\n\r\n  face = paper.ellipse(200,200,60,80)\r\n  face.attr(\"fill\", \"saddlebrown\")\r\n\r\n  leftEyeOuter = paper.ellipse(175, 175, 12,15).attr(\"fill\", \"white\")\r\n  leftEye = paper.ellipse(175, 170, 7, 7).attr(\"fill\", \"black\")\r\n  rightEyeOuter = paper.ellipse(225, 175, 12,15).attr(\"fill\", \"white\")\r\n  rightEye = paper.ellipse(225, 170, 7, 7).attr(\"fill\", \"black\")\r\n\r\n  nose = paper.ellipse(200, 273, 25,10).attr(\"fill\", \"black\")\r\n\r\n</code>",
 "spec"=>"assert(( -> $(\"svg\").length > 0), \"Just copy in the code from the directions and make sure you indent the code inside the function.\")\r\n\r\nassert(( -> $(\"svg ellipse\").length == 8), \"Make sure you copy *all* the code.\")",
 "success_message"=>"Woohoo! Cute dog. ",
 "position"=>1,
 "created_at"=>"2012-01-10 02:04:33 UTC",
 "updated_at"=>"2012-01-10 02:17:31 UTC",
 "title"=>"Draw the puppy",
 "hint"=>"We've put drawPuppy into a function. ",
 "solution"=>"\r\npaper = makeWorkspace()\r\n\r\n  leftEar=paper.ellipse(150,215,40,80)\r\n  leftEar.attr(\"fill\", \"saddleBrown\")\r\n  rightEar=paper.ellipse(250,215,40,80)\r\n  rightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\n  leftEar.transform(\"R20\")\r\n  rightEar.transform(\"R-20\")\r\n\r\n  face = paper.ellipse(200,200,60,80)\r\n  face.attr(\"fill\", \"saddlebrown\")\r\n\r\n  leftEyeOuter = paper.ellipse(175, 175, 12,15).attr(\"fill\", \"white\")\r\n  leftEye = paper.ellipse(175, 170, 7, 7).attr(\"fill\", \"black\")\r\n  rightEyeOuter = paper.ellipse(225, 175, 12,15).attr(\"fill\", \"white\")\r\n  rightEye = paper.ellipse(225, 170, 7, 7).attr(\"fill\", \"black\")\r\n\r\n  nose = paper.ellipse(200, 273, 25,10).attr(\"fill\", \"black\")",
 "image_url"=>"step8.png",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>27,
 "kit_id"=>3,
 "description"=>"Welcome to freeplay mode. \r\n\r\nYou can make your puppy do anything you want here. \r\n\r\nSome ideas of drawing methods you can use are: \r\n\r\n<code>paper.rect(center-x, center-y, width, height)</code>\r\n\r\n<code>paper.text(center-x, center-y, text)</code>\r\n\r\nYou can check <a href=\"http://raphaeljs.com/reference.html\" target=\"_blank\">Raphael JS</a>, our drawing library for more info on these and many other methods. \r\n\r\nFor a list of colors we recommend this <a href=\"http://www.w3schools.com/html/html_colornames.asp\" target=\"_blank\"> color names table</a>. \r\n\r\nHappy  coding!",
 "spec"=>"",
 "success_message"=>"",
 "position"=>10,
 "created_at"=>"2012-01-13 03:43:16 UTC",
 "updated_at"=>"2012-04-23 15:57:41 UTC",
 "title"=>"Let your creativity flow",
 "hint"=>"No hints- just follow your heart!",
 "solution"=>"",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>true,
 "more_info"=>""},
{"id"=>28,
 "kit_id"=>7,
 "description"=>"If you were to write out a quiz, the first thing you'd need is a piece of paper to write it on.  Same thing with our computer quiz&mdash;you need the equivalent of a piece of paper.  \r\n\r\nSo the first set of instructions we need to give to the computer will make the paper for the quiz. \r\nSo first type this:\r\n\r\n<code>paper = makeWorkspace()</code>\r\n\r\nand then hit \"run this\". ",
 "spec"=>"",
 "success_message"=>"What you've made by typing \"makeWorkspace()\" is an html canvas element.  It's the digital version of laying down a sheet of paper to begin writing on.",
 "position"=>1,
 "created_at"=>"2012-02-15 14:56:56 UTC",
 "updated_at"=>"2012-03-27 20:05:09 UTC",
 "title"=>"Creating the workspace",
 "hint"=>"Make sure you copied it exactly, when you're writing code it matters whether each letter is upper case or lower case. \r\n",
 "solution"=>"paper = makeWorkspace()",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>32,
 "kit_id"=>7,
 "description"=>"Now let's come up with some answers to choose from. \r\n\r\nHere's a couple to start you off: \r\n\r\n<code> answer1 = paper.text(200, 80, \"a little nippy out there\")  \r\nanswer2 = paper.text(200, 120, \"rainy rainy rain\") </code>\r\n\r\nMake sure you change the second number in text, making it larger will move each answer down the page. If you don't do this they might end up on top of each other!\r\n\r\nCreate at least 3 possible answers to your question. ",
 "spec"=>"",
 "success_message"=>"Awesome! Now there are some answers to choose from. ",
 "position"=>4,
 "created_at"=>"2012-02-29 20:32:30 UTC",
 "updated_at"=>"2012-03-27 20:07:42 UTC",
 "title"=>"I have an answer",
 "hint"=>"You will need to figure out the right placement of answers. The second number is the vertical placement. Try moving your answers up and down. ",
 "solution"=>"paper = makeWorkspace()\r\nbg = paper.rect(0,0,400, 400)\r\nbg.attr(\"fill\", \"yellow\")\r\nquestion = paper.text(200, 50, \"How cold is it today?\")\r\n\r\nanswer1 = paper.text(200, 80, \"a little nippy out there\") \r\nanswer2 = paper.text(200, 120, \"spring-like\") \r\nanswer3 = paper.text(200, 160, \"watch out for global warming\") ",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>31,
 "kit_id"=>7,
 "description"=>"So to make a quiz we will need to start with a question. \r\n\r\nJust like we drew a rectangle before, now we can do some writing. \r\n\r\nTry:\r\n<code>question=paper.text(200,50,\"How cold is it today?\")</code>\r\n\r\nThe first 2 numbers are the x and y coordinates. \r\n\r\n**HINT: try highlighting a number and using the up and down arrows to move the question around the paper.**\r\n\r\nIf you want we can also change around the colors and fonts a bit by using \"attr\".\r\n\r\nTry this:\r\n\r\n<code>question.attr(\"fill\" : \"white\", \"font-family\" : \"Helvetica\", \"font-size\" : 20) </code>\r\n\r\nYou can adjust the fill color, font-family and font-size to change the look. \r\n  ",
 "spec"=>"",
 "success_message"=>"Now you have a question, but it's not very interesting. Why don't you try changing it to something you come up with? ",
 "position"=>3,
 "created_at"=>"2012-02-29 20:13:01 UTC",
 "updated_at"=>"2012-03-27 20:07:33 UTC",
 "title"=>"That is the question",
 "hint"=>"",
 "solution"=>"paper = makeWorkspace() \r\nbackground = paper.rect(0,0,400,400) \r\nbackground.attr(\"fill\", \"royalblue\")\r\n\r\nquestion = paper.text(200, 50, \"How cold is it today?\")",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>39,
 "kit_id"=>7,
 "description"=>"Congratulations, you now know the basics of creating a quiz. Let's continue to improve it! \r\n\r\nHere are some resources to help you out: \r\n\r\n<a href=\"http://raphaeljs.com/reference.html\" target=\"_blank\">Raphael</a> is the library we used to to make the paper, the rectangles, the text and  click on things. Check here for some more good stuff (you could try an image question perhaps or change around your fonts).\r\n\r\nAgain, here is the <a href='http://www.w3schools.com/html/html_colornames.asp'>color list</a>.\r\n\r\nTry changing around the fonts and colors:\r\n<code>question.attr(\"fill\" : \"white\", \"font-family\" : \"Helvetica\", \"font-size\" : 20) </code>\r\n\r\n",
 "spec"=>nil,
 "success_message"=>"",
 "position"=>10,
 "created_at"=>"2012-03-01 18:20:31 UTC",
 "updated_at"=>"2012-03-27 20:08:38 UTC",
 "title"=>"Let your creativity flow",
 "hint"=>"You probably want to add reset to the last question only. ",
 "solution"=>"",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>true,
 "more_info"=>""},
{"id"=>45,
 "kit_id"=>10,
 "description"=>"Before we program the game we need to draw the mole. We're going to use one we've already drawn for you.\r\n<code><num>13\r\n|\r\n</num><add>mole = paper.image('http://localhost:5000/assets/mole.png', 6, 10, 80, 80)</add></code>",
 "spec"=>nil,
 "success_message"=>"You can use a different image if you want. Try using google image search and substituting a different url.",
 "position"=>5,
 "created_at"=>"2012-03-23 14:55:51 UTC",
 "updated_at"=>"2012-03-28 16:38:41 UTC",
 "title"=>"Now for the mole",
 "hint"=>"",
 "solution"=>"paper = makeWorkspace() \r\nbackground = paper.rect(0,0,400,400) \r\nbackground.attr('fill':'deepskyblue')\r\nmolehole = paper.circle(50,50,30).attr('fill':'navy', 'stroke-width': 0)\r\n_(4).times( (i) ->\r\n&nbsp;&nbsp;_(4).times( (j) ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveLeft = i * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveRight = j * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;molehole.clone().transform(\"T\" + moveLeft + \",\" + moveDown)\r\n&nbsp;&nbsp;)\r\n)\r\nmole = paper.image('http://localhost:5000/assets/mole.png', 6, 10, 80, 80)",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>21,
 "kit_id"=>4,
 "description"=>"The ears look a little droopy&mdash; let's try to rotate them. \r\n\r\nA paper ellipse has a method called \"transform\" where you can pass in a string showing how you want to transform the object. If you pass in \"R\" for rotate followed by the number of degrees you want to rotate you can make the ears rotate around their center. \r\n\r\nTry rightEar.transform(\"R90\"). Now adjust the angle so that it looks like the picture. \r\n\r\nTry it with a negative angle for the left ear. ",
 "spec"=>"",
 "success_message"=>"Looking good dawg. ",
 "position"=>6,
 "created_at"=>"2012-01-06 15:46:21 UTC",
 "updated_at"=>"2012-01-06 16:12:08 UTC",
 "title"=>"Perk up the ears",
 "hint"=>"For the left ear try leftEar.transform(\"R-80\"), see if you can adjust that negative angle to match the picture. ",
 "solution"=>"paper = makeWorkspace()\r\n\r\nleftEar=paper.ellipse(150,215,40,80)\r\nleftEar.attr(\"fill\", \"saddleBrown\")\r\nrightEar=paper.ellipse(250,215,40,80)\r\nrightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\nleftEar.transform(\"R20\")\r\nrightEar.transform(\"R-20\")\r\n\r\n\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")\r\n",
 "image_url"=>nil,
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>15,
 "kit_id"=>3,
 "description"=>"The ears look a little droopy&mdash; let's try to rotate them. \r\n\r\nYour ellipses have a method called rotate. Here is the code for the right ear:\r\n\r\n<code><add>rightEar.rotate(\"340\")</add></code>\r\nNow try to rotate the left ear in a similar manner. ",
 "spec"=>"assert( (-> \r\n  rotatedEllipses = 0\r\n  _.each($frame.find(\"svg ellipse\"), (ellipse)-> \r\n    if $(ellipse).attr(\"transform\") \r\n      rotatedEllipses += 1\r\n  )\r\n  if rotatedEllipses < 2\r\n    return false\r\n  else\r\n    return true\r\n), \"You need to rotate both ears\")",
 "success_message"=>"You successfully used rotate. When you use \"20\" you rotated the ear 20&deg; clockwise. ",
 "position"=>7,
 "created_at"=>"2012-01-06 15:46:21 UTC",
 "updated_at"=>"2012-04-23 19:10:12 UTC",
 "title"=>"Perk up the ears",
 "hint"=>"For the left ear try <code>leftEar.rotate(\"20\")</code>",
 "solution"=>"paper = makeWorkspace()\r\n\r\nleftEar=paper.ellipse(150,215,40,80)\r\nleftEar.attr(\"fill\", \"saddleBrown\")\r\nrightEar=paper.ellipse(250,215,40,80)\r\nrightEar.attr(\"fill\", \"saddleBrown\")\r\n\r\nleftEar.rotate(\"20\")\r\nrightEar.rotate(\"340\")\r\n\r\n\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")\r\n",
 "image_url"=>"step6.png",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>30,
 "kit_id"=>7,
 "description"=>"The way we will change the background color is to place a colored rectangle over the grid. In the program we are using you can't actually change the color of the background so the next best thing to do is put something on top of it. It's like putting a tablecloth over your table. \r\n\r\nTo make a rectangle, type:\r\n\r\n<code>background = paper.rect(0,0,400,400)</code>\r\n\r\nThen: \r\n\r\n<code>background.attr(\"fill\", \"royalblue\")</code>\r\n\r\n**HINT: try highlighting \"royalblue\" and pressing the up and down arrows in order to try more colors**\r\n\r\nWe gave the rectangle the nickname \"background\" because we still wanted to talk to it. ",
 "spec"=>"",
 "success_message"=>"Great, you made a background rectangle and filled it in with royal blue. \r\n\r\nIf you want to change the color now try one of <a href='http://w3schools.com/html/html_colornames.asp' target=\"_blank\">these</a>.",
 "position"=>2,
 "created_at"=>"2012-02-15 20:47:26 UTC",
 "updated_at"=>"2012-03-27 20:06:42 UTC",
 "title"=>"Background Color",
 "hint"=>"",
 "solution"=>"paper = makeWorkspace()\r\nbackground = paper.rect(0,0,400,400)\r\nbackground.attr(\"fill\", \"royalblue\")",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>"You'll also notice that we used paper again, that nickname allowed us to add things to the paper. We'll continue to use that as we build up our game. \r\n\r\nThe first line of code creates a square. The x,y coordinates were set by the first 2 numbers used by the rectangle. The height and width were set by the last 2 numbers.\r\n\r\nLastly, we added the color by setting the \"fill\" attribute of the background. "},
{"id"=>25,
 "kit_id"=>4,
 "description"=>"The first thing we will draw is the face. We will use a long oval&mdash; also known as an <a href=\"http://www.merriam-webster.com/dictionary/ellipse\">ellipse</a>. \r\n\r\nYour paper has a method called ellipse but in order to use it we need a reference to the paper object. To do this we will set a variable. We set variables like so:\r\n\r\n<code>x = 1</code>\r\n\r\nNow the variable called <code>x</code> has the value 1. Try setting a variable called <code>paper</code> to the value of <code>makeWorkspace()</code>. Once you've done that it would be a good time to click run it to see if you have that bit correct. Did it work? OK, now we need to draw our ellipse on the paper. Ellipses look like this:\r\n\r\n<code>paper.ellipse(center-horizontal, center-vertical, width, height)</code>\r\n\r\nwhere center-horizontal is the oval's position left to right on the paper, center-vertical is the oval's position top to bottom, and width and height control the size of the oval.\r\n\r\nLet\\'s make an oval in the center of our paper, at center-vertical 200, center-horizontal 200, and with a width of 60 and a height of 80",
 "spec"=>"assert(( -> \r\n  try\r\n    paper\r\n  catch error\r\n    false\r\n), \"You need to set a variable called paper\")\r\nassert((-> window._paper == paper), \"You need to set the paper variable equal to makeWorkspace()\")\r\n\r\nassert((->$(\"svg ellipse\").length > 0), \"You need to add an ellipse by calling paper.ellipse()\")",
 "success_message"=>"Great work. Our puppy has a head. He\"ll need that.",
 "position"=>2,
 "created_at"=>"2012-01-05 22:39:34 UTC",
 "updated_at"=>"2012-02-29 22:23:18 UTC",
 "title"=>"Puppy Face",
 "hint"=>"This would make an ellipse at 100 left, 100 down, and with a width of 40 and a height of 60:\r\n\r\npaper = makeWorkspace()\r\npaper.ellipse(100, 100, 40, 60)\r\n\r\nHow can we make an ellipse at 200 left, 200 down, and with a width of 60 and a height of 80?",
 "solution"=>"paper = makeWorkspace()\r\nface=paper.ellipse(200,200,60,80)",
 "image_url"=>nil,
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>nil},
{"id"=>52,
 "kit_id"=>10,
 "description"=>"Now we actually want to use the start button to start our game. Add these lines<code><num>42\r\n43\r\n44\r\n45\r\n46\r\n47\r\n48\r\n49\r\n50\r\n51\r\n</num><add>button.click( () ->\r\n&nbsp;&nbsp;button.hide()\r\n&nbsp;&nbsp;text.hide()\r\n&nbsp;&nbsp;showMole()\r\n)\r\ntext.click( () ->\r\n&nbsp;&nbsp;button.hide()\r\n&nbsp;&nbsp;text.hide()\r\n&nbsp;&nbsp;showMole()\r\n)</add></code>\r\n\r\nThis should go at the very end of your program. ",
 "spec"=>nil,
 "success_message"=>"Click start and see what happens.",
 "position"=>10,
 "created_at"=>"2012-03-26 14:27:59 UTC",
 "updated_at"=>"2012-03-28 16:28:39 UTC",
 "title"=>"Start the game",
 "hint"=>"",
 "solution"=>"paper = makeWorkspace() \r\nbackground = paper.rect(0,0,400,400) \r\nbackground.attr('fill':'deepskyblue')\r\nmolehole = paper.circle(50,50,30).attr('fill':'navy', 'stroke-width': 0)\r\n_(4).times( (i) ->\r\n&nbsp;&nbsp;_(4).times( (j) ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveLeft = i * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveRight = j * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;molehole.clone().transform(\"T\" + moveLeft + \",\" + moveDown)\r\n&nbsp;&nbsp;)\r\n)\r\nmole = paper.image('http://localhost:5000/assets/mole.png', 6, 10, 80, 80)\r\n$('body').append($(\"&lt;div id='sound'&gt;\"))\r\nplaySound = (src) ->\r\n&nbsp;&nbsp;$(\"#sound\").html(\"&lt;embed src='\"+src+\"' hidden='true' autostart='true' loop='false'&gt;\")<br />\r\nmole.click(->\r\n&nbsp;&nbsp;playSound(\"http://localhost:5000/assets/punch.wav\")\r\n)\r\nmole.hide()\r\nrandom = ->\r\n&nbsp;&nbsp;Math.floor(Math.random() * 4) * 100\r\ncount = 0\r\nshowMole = ->\r\n&nbsp;&nbsp;mole.animate\r\n&nbsp;&nbsp;&nbsp;&nbsp;x:6 + random(), y:10 + random(), 1700, \r\n&nbsp;&nbsp;&nbsp;&nbsp;() ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.show()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setTimeout(( ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.hide()  \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count++\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if count < 15\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;showMole()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count = 0\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;), 900)\r\nbutton = paper.rect(123, 170, 150, 60)\r\nbutton.attr(\"fill\":'deeppink', 'stroke':'white', 'stroke-width':'3', 'r':12)\r\ntext = paper.text(200, 200, \"Start\" )\r\ntext.attr('font-size':24, 'font-family':'monospace', 'fill': 'yellowgreen', 'font-weight':'bold')\r\nbutton.click( () ->\r\n&nbsp;&nbsp;button.hide()\r\n&nbsp;&nbsp;text.hide()\r\n&nbsp;&nbsp;showMole()\r\n)\r\ntext.click( () ->\r\n&nbsp;&nbsp;button.hide()\r\n&nbsp;&nbsp;text.hide()\r\n&nbsp;&nbsp;showMole()\r\n)",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>41,
 "kit_id"=>10,
 "description"=>"We need to create a piece of paper. \r\nType this <i>exactly</i> into your code area: \r\n\r\n<code><num>1</num><add>paper = makeWorkspace()</add></code>",
 "spec"=>nil,
 "success_message"=>"You made a canvas. The rest of your game will be created on this. ",
 "position"=>1,
 "created_at"=>"2012-03-20 19:15:32 UTC",
 "updated_at"=>"2012-03-28 15:58:35 UTC",
 "title"=>"Make a paper",
 "hint"=>"make sure that you use the exact capitalization in the example. Also, don't forget the parentheses. ",
 "solution"=>"paper = makeWorkspace()",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>43,
 "kit_id"=>10,
 "description"=>"We need holes for the moles to pop out of. Type this:\r\n<code><num>4\r\n5\r\n</num><add>molehole = paper.circle(50,50,30)\r\nmolehole.attr('fill':'navy', 'stroke-width': 0)</add></code>",
 "spec"=>nil,
 "success_message"=>"Try changing the parameters of the circle (the green numbers inside the parentheses) by highlighting them and using the up/down arrows on your keyboard. \r\nSee if you can figure out what each number controls.\r\n",
 "position"=>3,
 "created_at"=>"2012-03-23 14:47:27 UTC",
 "updated_at"=>"2012-03-28 16:30:56 UTC",
 "title"=>"Mole hole",
 "hint"=>"The radius of the circle (3rd number) must be 30, the stroke-width in the attr list must be 0. ",
 "solution"=>"paper = makeWorkspace() \r\nbackground = paper.rect(0,0,400,400) \r\nbackground.attr('fill':'deepskyblue')\r\nmolehole = paper.circle(50,50,30).attr('fill':'navy', 'stroke-width': 0)",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>12,
 "kit_id"=>3,
 "description"=>"Now we want to make the puppy's face brown. \r\n\r\nWe can use face.attr (short for <span style=\"font-style:italic\">attribute</span>) to set the color attribute. \r\n\r\n<code><num>3</num><add>face.attr(\"fill\", \"saddlebrown\")</add></code>\r\n\r\n**HINT: try highlighting \"saddlebrown\" and pressing the up and down arrows to see more color choices. ** \r\n",
 "spec"=>"assert(( -> _.find($frame.find(\"svg ellipse\"),((e)-> $(e).attr(\"fill\").match(/#/i)))), \"Set the face color to saddlebrown\")",
 "success_message"=>"You added color to the puppy's face by setting the fill attribute (that's what it means when you type attr) of it's face. We used saddlebrown but you can try other colors as well if you like.",
 "position"=>4,
 "created_at"=>"2012-01-06 00:39:08 UTC",
 "updated_at"=>"2012-04-23 17:02:53 UTC",
 "title"=>"Adding Some Color",
 "hint"=>"Make sure the name of the color is surrounded by quotes. ",
 "solution"=>"paper = makeWorkspace()\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>55,
 "kit_id"=>10,
 "description"=>"You can use the <a href='http://raphaeljs.com/reference.html' target='_blank'>Raphael JS library</a> to make your game even better. \r\n\r\n",
 "spec"=>nil,
 "success_message"=>"",
 "position"=>12,
 "created_at"=>"2012-03-27 14:45:43 UTC",
 "updated_at"=>"2012-03-27 14:46:52 UTC",
 "title"=>"Make the mole even better!",
 "hint"=>"",
 "solution"=>"",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>true,
 "more_info"=>""},
{"id"=>42,
 "kit_id"=>10,
 "description"=>"Now we need to make a background for our paper. Let's make it deepskyblue. Go to a new line in your code and type: \r\n<code><num>2\r\n3\r\n</num><add>background = paper.rect(0,0,400,400)\r\nbackground.attr('fill':'deepskyblue')</add></code>",
 "spec"=>nil,
 "success_message"=>"Try this: Use your mouse to highlight the word 'deepskyblue' in your code, then use the up and down arrows to try out different colors. ",
 "position"=>2,
 "created_at"=>"2012-03-20 19:16:22 UTC",
 "updated_at"=>"2012-03-28 16:31:20 UTC",
 "title"=>"Background Color",
 "hint"=>"make sure you did not delete your first line, it's still important!\r\nThe first line should be: <code>paper = makeWorkspace()</code>",
 "solution"=>"paper = makeWorkspace()\r\nbackground = paper.rect(0,0,400,400)\r\nbackground.attr('fill':'deepskyblue')",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>49,
 "kit_id"=>10,
 "description"=>"Let's write some code so that the mole will pop up in a random spot. Add this to the end of your program.\r\n<code><num>21\r\n22\r\n23\r\n24\r\n25\r\n26\r\n27\r\n28\r\n29\r\n</num><add>mole.hide()\r\nrandom = ->\r\n&nbsp;&nbsp;Math.floor(Math.random() * 4) * 100\r\nshowMole = ->\r\n&nbsp;&nbsp;mole.animate\r\n&nbsp;&nbsp;&nbsp;&nbsp;x:6 + random(), y:10 + random(), 1700, \r\n&nbsp;&nbsp;&nbsp;&nbsp;() ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.show()\r\nshowMole()</add></code>",
 "spec"=>nil,
 "success_message"=>"Experiment with adding and removing the lines mole.hide(), mole.show() and showMole(). How do these affect what you see on the right? ",
 "position"=>7,
 "created_at"=>"2012-03-23 21:55:04 UTC",
 "updated_at"=>"2012-03-28 16:21:21 UTC",
 "title"=>"Where's the mole?",
 "hint"=>"If the mole is popping up in a random spot but you can't progress, try refreshing the page. Sometimes these things happen... ",
 "solution"=>"paper = makeWorkspace() \r\nbackground = paper.rect(0,0,400,400) \r\nbackground.attr('fill':'deepskyblue')\r\nmolehole = paper.circle(50,50,30).attr('fill':'navy', 'stroke-width': 0)\r\n_(4).times( (i) ->\r\n&nbsp;&nbsp;_(4).times( (j) ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveLeft = i * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveRight = j * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;molehole.clone().transform(\"T\" + moveLeft + \",\" + moveDown)\r\n&nbsp;&nbsp;)\r\n)\r\nmole = paper.image('http://localhost:5000/assets/mole.png', 6, 10, 80, 80)\r\n$('body').append($(\"&lt;div id='sound'&gt;\"))\r\nplaySound = (src) ->\r\n&nbsp;&nbsp;$(\"#sound\").html(\"&lt;embed src='\"+src+\"' hidden='true' autostart='true' loop='false'&gt;\")<br />\r\nmole.click(->\r\n&nbsp;&nbsp;playSound(\"http://localhost:5000/assets/punch.wav\")\r\n)\r\nmole.hide()\r\nrandom = ->\r\n&nbsp;&nbsp;Math.floor(Math.random() * 4) * 100\r\nshowMole = ->\r\n&nbsp;&nbsp;mole.animate\r\n&nbsp;&nbsp;&nbsp;&nbsp;x:6 + random(), y:10 + random(), 1700, \r\n&nbsp;&nbsp;&nbsp;&nbsp;() ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.show()\r\nshowMole()",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>48,
 "kit_id"=>10,
 "description"=>"When we whack the mole let's play a sound. Type this into the end of your program.\r\n<code><num>14\r\n15\r\n16\r\n|\r\n17\r\n18\r\n19\r\n20\r\n</num><add>$('body').append($(\"&lt;div id='sound'&gt;\"))\r\nplaySound = (src) ->\r\n&nbsp;&nbsp;$(\"#sound\").html(\"&lt;embed src='\"+src+\"' hidden='true' autostart='true' loop='false'&gt;\")<br />\r\nmole.click(->\r\n&nbsp;&nbsp;playSound(\"http://localhost:5000/assets/punch.wav\")\r\n)</add></code>\r\nNow when you click the mole a sound will play- try it!",
 "spec"=>nil,
 "success_message"=>"Try changing the url for playSound to point to a new sound file. We used soundbible.com.",
 "position"=>6,
 "created_at"=>"2012-03-23 21:42:53 UTC",
 "updated_at"=>"2012-03-28 16:29:44 UTC",
 "title"=>"Whack the mole",
 "hint"=>"Make sure you type everything with the correct spacing. ",
 "solution"=>"paper = makeWorkspace() \r\nbackground = paper.rect(0,0,400,400) \r\nbackground.attr('fill':'deepskyblue')\r\nmolehole = paper.circle(50,50,30).attr('fill':'navy', 'stroke-width': 0)\r\n_(4).times( (i) ->\r\n&nbsp;&nbsp;_(4).times( (j) ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveLeft = i * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveRight = j * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;molehole.clone().transform(\"T\" + moveLeft + \",\" + moveDown)\r\n&nbsp;&nbsp;)\r\n)\r\nmole = paper.image('http://localhost:5000/assets/mole.png', 6, 10, 80, 80)\r\n$('body').append($(\"&lt;div id='sound'&gt;\"))\r\nplaySound = (src) ->\r\n&nbsp;&nbsp;$(\"#sound\").html(\"&lt;embed src='\"+src+\"' hidden='true' autostart='true' loop='false'&gt;\")<br />\r\nmole.click(->\r\n&nbsp;&nbsp;playSound(\"http://localhost:5000/assets/punch.wav\")\r\n)",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>54,
 "kit_id"=>10,
 "description"=>"*IMPORTANT*\r\nIn the samples below, the green lines should be added to your code. The non-colored lines are already in your code and are just for reference.  <code> <num>24\r\n25\r\n26\r\n27\r\n28\r\n29\r\n30\r\n31\r\n32\r\n33\r\n34\r\n35\r\n36\r\n37\r\n38\r\n</num><add>count = 0</add>\r\nshowMole = ->\r\n&nbsp;&nbsp;mole.animate\r\n&nbsp;&nbsp;&nbsp;&nbsp;x:6 + random(), y:10 + random(), 1700, \r\n&nbsp;&nbsp;&nbsp;&nbsp;() -> \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.show()\r\n<add>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setTimeout(( ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.hide()  \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count++\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if count < 15\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;showMole()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count = 0\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;), 900)</add>\r\nshowMole()</code>\r\n\r\nIf you're having trouble, try deleting the end of your code, starting at showMole = -> and pasting in the entire example. \r\n",
 "spec"=>nil,
 "success_message"=>"This step was really hard, you are awesome! In CoffeeScript all the spacing matters so it can be tricky to get right. ",
 "position"=>8,
 "created_at"=>"2012-03-26 15:16:56 UTC",
 "updated_at"=>"2012-03-28 16:23:54 UTC",
 "title"=>"Move the mole",
 "hint"=>"Make sure that the indentation is consistent or your code will not work properly. ",
 "solution"=>"paper = makeWorkspace() \r\nbackground = paper.rect(0,0,400,400) \r\nbackground.attr('fill':'deepskyblue')\r\nmolehole = paper.circle(50,50,30).attr('fill':'navy', 'stroke-width': 0)\r\n_(4).times( (i) ->\r\n&nbsp;&nbsp;_(4).times( (j) ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveLeft = i * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveRight = j * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;molehole.clone().transform(\"T\" + moveLeft + \",\" + moveDown)\r\n&nbsp;&nbsp;)\r\n)\r\nmole = paper.image('http://localhost:5000/assets/mole.png', 6, 10, 80, 80)\r\n$('body').append($(\"&lt;div id='sound'&gt;\"))\r\nplaySound = (src) ->\r\n&nbsp;&nbsp;$(\"#sound\").html(\"&lt;embed src='\"+src+\"' hidden='true' autostart='true' loop='false'&gt;\")<br />\r\nmole.click(->\r\n&nbsp;&nbsp;playSound(\"http://localhost:5000/assets/punch.wav\")\r\n)\r\nmole.hide()\r\nrandom = ->\r\n&nbsp;&nbsp;Math.floor(Math.random() * 4) * 100\r\ncount = 0\r\nshowMole = ->\r\n&nbsp;&nbsp;mole.animate\r\n&nbsp;&nbsp;&nbsp;&nbsp;x:6 + random(), y:10 + random(), 1700, \r\n&nbsp;&nbsp;&nbsp;&nbsp;() ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.show()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setTimeout(( ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.hide()  \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count++\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if count < 15\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;showMole()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count = 0\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;), 900)\r\nshowMole()",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>35,
 "kit_id"=>7,
 "description"=>"We are going to make an alert pop up once you click on the correct answer. In the same way that we were able to use \"attr\" to set attributes, we can use \"click\" to decide what happens when we click. \r\n\r\nThe way we write it is this (and don't worry that it looks a little weird , this is just the way you talk to a computer)\r\n\r\n<code>answer3.click(->\r\n&nbsp;&nbsp;alert(\"Correct!\")\r\n)</code>\r\n",
 "spec"=>"",
 "success_message"=>"Amazing! Now try clicking on the correct answer. \r\n",
 "position"=>5,
 "created_at"=>"2012-02-29 22:50:14 UTC",
 "updated_at"=>"2012-03-27 20:07:51 UTC",
 "title"=>"Bringing it all together",
 "hint"=>"answer3 may not be the correct answer- make sure you use the actual name of the answer you've chosen. ",
 "solution"=>"paper = makeWorkspace()\r\nbg = paper.rect(0,0,400, 400)\r\nbg.attr(\"fill\", \"yellow\")\r\nquestion = paper.text(200, 50, \"How cold is it today?\")\r\n\r\nanswer1 = paper.text(200, 80, \"a little nippy out there\") \r\nanswer2 = paper.text(200, 120, \"spring-like\") \r\nanswer3 = paper.text(200, 160, \"watch out for global warming\") \r\n\r\ncorrectAnswer = ->\r\n&nbsp;&nbsp;alert(\"Correct!\")\r\n\r\nanswer3.click( ->\r\n&nbsp;&nbsp;alert(\"Correct!\")\r\n)",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>"Click works by taking some code and running it when the object is clicked, in this case, the answer.\r\n\r\nRun your code and try it out!"},
{"id"=>36,
 "kit_id"=>7,
 "description"=>"Now that we know how to write a question let's add more questions to the quiz. \r\n\r\nTo do that we need to wipe away the last question after you get it right.\r\n\r\nLet's start out with making a new background for the new question. Change your click to read: \r\n<code>answer3.click( ->\r\n&nbsp;&nbsp;alert(\"Correct!\")\r\n&nbsp;&nbsp;background = paper.rect(0,0,400,400)\r\n&nbsp;&nbsp;background.attr(\"fill\", \"yellow\")\r\n)</code>",
 "spec"=>"",
 "success_message"=>"Try running your quiz and selecting the correct answer. The background should change colors and the question should disappear. ",
 "position"=>6,
 "created_at"=>"2012-03-01 16:47:41 UTC",
 "updated_at"=>"2012-03-27 20:07:59 UTC",
 "title"=>"Starting the next question",
 "hint"=>"Make sure that when you set the background color the second time it is in line with the alert. If not, it won't work. ",
 "solution"=>"paper = makeWorkspace()\r\nbg = paper.rect(0,0,400, 400)\r\nbg.attr(\"fill\", \"yellow\")\r\nquestion = paper.text(200, 50, \"How cold is it today?\")\r\n\r\nanswer1 = paper.text(200, 80, \"a little nippy out there\") \r\nanswer2 = paper.text(200, 120, \"spring-like\") \r\nanswer3 = paper.text(200, 160, \"watch out for global warming\") \r\n\r\nanswer3.click(->\r\n&nbsp;&nbsp;alert(\"Correct!\")\r\n&nbsp;&nbsp;background = paper.rect(0,0,400,400)\r\n&nbsp;&nbsp;background.attr(\"fill\", \"yellow\")\r\n)\r\n",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>"We are doing the exact same thing we did to make the first background, except this time it's yellow!\r\n\r\nIf you want to try another color you can look <a href=\"http://www.w3schools.com/html/html_colornames.asp\" target='_blank'>here</a> for ideas. "},
{"id"=>44,
 "kit_id"=>10,
 "description"=>"Whack-a-mole with only one hole is not that interesting. Let's make some more:\r\n<code><num>6\r\n7\r\n8\r\n9\r\n10\r\n|\r\n11\r\n12\r\n</num><add>_(4).times( (i) ->\r\n&nbsp;&nbsp;_(4).times( (j) ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveLeft = i * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveDown = j * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;molehole.clone().transform(\"T\" + moveLeft + \",\" + moveDown)\r\n&nbsp;&nbsp;)\r\n)</add></code>",
 "spec"=>nil,
 "success_message"=>"Notice that the numbers in your code are green. You can highlight them and press the up and down arrows on your keyboard to figure out how they affect the picture on the right. ",
 "position"=>4,
 "created_at"=>"2012-03-23 14:52:38 UTC",
 "updated_at"=>"2012-03-28 16:30:14 UTC",
 "title"=>"More holes!",
 "hint"=>"The spacing here is very important. Make sure it's exactly the same as in the example.\r\n\r\nThe original mole hole needs to have a radius of 30. Make sure that the last number in the molehole is 30. ",
 "solution"=>"paper = makeWorkspace() \r\nbackground = paper.rect(0,0,400,400) \r\nbackground.attr('fill':'deepskyblue')\r\nmolehole = paper.circle(50,50,30).attr('fill':'navy', 'stroke-width': 0)\r\n_(4).times( (i) ->\r\n&nbsp;&nbsp;_(4).times( (j) ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveLeft = i * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveRight = j * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;molehole.clone().transform(\"T\" + moveLeft + \",\" + moveDown)\r\n&nbsp;&nbsp;)\r\n)",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>10,
 "kit_id"=>3,
 "description"=>"We need to save what you just made to a variable (like a nickname, so we can tell it to do stuff later).  Let's call it \"paper.\"\r\n\r\nGo back to line 1 and change it- the red means \"remove this code\" and the green means: \"add this code\"\r\n\r\n<code><num>1\r\n1\r\n</num><delete>makeWorkspace()</delete>\r\n<add>paper = makeWorkspace()</add></code>\r\n\r\nNow that you gave it a name, the computer will know what you're talking about when you want to use it later.",
 "spec"=>"assert((->$frame.find(\"svg ellipse\").length > 0), \"Add an ellipse for the face\")\r\n\r\nassert((->$frame.find(\"svg ellipse\").first().attr(\"rx\") == \"60\"), \"Make the width 60\")\r\n\r\nassert((->$frame.find(\"svg ellipse\").first().attr(\"ry\") == \"80\"), \"Make the height 80\")\r\n",
 "success_message"=>"Great, you've made your first variable!",
 "position"=>2,
 "created_at"=>"2012-01-05 22:39:34 UTC",
 "updated_at"=>"2012-04-23 16:12:30 UTC",
 "title"=>"Variables = Nicknames",
 "hint"=>"Make sure you removed the old first line and added the new one that starts with paper =",
 "solution"=>"paper = makeWorkspace()",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>13,
 "kit_id"=>3,
 "description"=>"Our puppy needs ears. Let's make 2 ellipses on the side of the head. \r\n\r\nHere's the code for the left ear. \r\n\r\n<code><add>leftEar = paper.ellipse(150,215,40,80)</add></code>\r\n\r\nTry the right one on your own. The first number after the parentheses represents the distance from the left side of the paper. The middle point is 200 - so 150 is 50 units to the left of center. Make the right ear 50 units to the right of the center.\r\n\r\n**HINT: try highlighting any of the numbers and pressing the up and down arrows to move the ears around on the page and place them correctly. ** ",
 "spec"=>"assert( (-> ($frame.find(\"svg ellipse\").length > 2)), \"Add 2 new ellipses for the ears.\")\r\n\r\nassert( (-> ($frame.find(\"svg ellipse[cx=150]\").length != 2)), \"Set the x-coordinate (first number in the ellipse method) to be different for the second ear.\")\r\n\r\n\r\nassert( (-> \r\n  ellipses = 0\r\n  _.each($frame.find(\"svg ellipse\"), (ellipse)-> \r\n    if $(ellipse).attr(\"rx\") > 35 && $(ellipse).attr(\"rx\") < 45\r\n      ellipses += 1\r\n  )\r\n  if ellipses < 2\r\n    return false\r\n  else\r\n    return true\r\n), \"Give ears x-radius (the third number in the ellipse method) of approximately 40\")\r\n\r\n\r\nassert( (-> \r\n  ellipses = 0\r\n  _.each($frame.find(\"svg ellipse\"), (ellipse)-> \r\n    if $(ellipse).attr(\"ry\") > 75 && $(ellipse).attr(\"ry\") < 85\r\n      ellipses += 1\r\n  )\r\n  if ellipses < 2\r\n    return false\r\n  else\r\n    return true\r\n), \"Give ears y-radius (the fourth number in the ellipse method) of approximately 80\")",
 "success_message"=>"you've added 2 new ellipses to your page for the ears. Are you getting the hang of the ellipse method? Again- the first two numbers are x and y (you can see them in the grid). The last two are width and height to give the ellipse size and stretch it out.",
 "position"=>5,
 "created_at"=>"2012-01-06 00:48:29 UTC",
 "updated_at"=>"2012-04-23 19:03:22 UTC",
 "title"=>"Do your ears hang low?",
 "hint"=>"<code><add>rightEar=paper.ellipse(250,215,40,80)</add></code>\r\n",
 "solution"=>"paper = makeWorkspace()\r\n\r\nleftEar=paper.ellipse(150,215,40,80)\r\n\r\nrightEar=paper.ellipse(250,215,40,80)\r\n\r\nface = paper.ellipse(200,200,60,80)\r\nface.attr(\"fill\", \"saddlebrown\")",
 "image_url"=>"step4.jpg",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>38,
 "kit_id"=>7,
 "description"=>"The last thing we need for the second question is an indicator that you have the correct answer. Let's do something similar to the first question. \r\n\r\nWhat we'll do is add a click to answer2 (or whichever one is right). We'll have to make another function with the code we want to save for when the  \r\n\r\n<code>answer3.click( ->\r\n&nbsp;&nbsp;....\r\n&nbsp;&nbsp;answer2.click(->\r\n&nbsp;&nbsp;&nbsp;&nbsp;alert(\"correct!\")\r\n&nbsp;&nbsp;)\r\n)</code>",
 "spec"=>"",
 "success_message"=>"Your quiz now has 2 questions. Try it out to make sure it works alright then click next to see it on its own page.",
 "position"=>8,
 "created_at"=>"2012-03-01 17:06:07 UTC",
 "updated_at"=>"2012-03-27 20:08:19 UTC",
 "title"=>"And another answer",
 "hint"=>"",
 "solution"=>"paper = makeWorkspace()\r\nbg = paper.rect(0,0,400, 400)\r\nbg.attr(\"fill\", \"yellow\")\r\nquestion = paper.text(200, 50, \"How cold is it today?\")\r\n\r\nanswer1 = paper.text(200, 80, \"a little nippy out there\") \r\nanswer2 = paper.text(200, 120, \"spring-like\") \r\nanswer3 = paper.text(200, 160, \"watch out for global warming\") \r\n\r\nanswer3.click( ->\r\n&nbsp;&nbsp;alert(\"Correct!\")\r\n&nbsp;&nbsp;background = paper.rect(0,0,400,400)\r\n&nbsp;&nbsp;background.attr(\"fill\", \"yellow\")\r\n&nbsp;&nbsp;question = paper.text(200, 50, \"How warm is it today?\")\r\n&nbsp;&nbsp;answer1 = paper.text(200, 80, \"sweltering\") \r\n&nbsp;&nbsp;answer2 = paper.text(200, 120, \"ouch, that burns!\") \r\n&nbsp;&nbsp;answer3 = paper.text(200, 160, \"rainy\")\r\n&nbsp;&nbsp;answer2.click(->\r\n&nbsp;&nbsp;&nbsp;&nbsp;alert(\"Correct!\")\r\n&nbsp;&nbsp;)\r\n)\r\n",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>56,
 "kit_id"=>3,
 "description"=>"To draw the face, we'll use an oval, also called an ellipse. \r\n\r\nTo do this, use the old nickname \"paper\" and add a \".\" followed by the thing you want to draw- in this case ellipse.\r\n\r\nThe green means \"add this code to the end of you program\"\r\n\r\n<code><num>2</num><add>face = paper.ellipse(200, 200, 60, 80)</add></code>\r\n\r\n",
 "spec"=>nil,
 "success_message"=>"You just drew an ellipse on the page. An ellipse is like a circle but more stretched out. Remember- you wrote paper.ellipse followed by four numbers. The first two numbers were the position from the left and top. The second two were width and height. If you made width and height the same you would have a circle! ",
 "position"=>3,
 "created_at"=>"2012-04-23 16:08:47 UTC",
 "updated_at"=>"2012-04-23 16:08:47 UTC",
 "title"=>"Puppy face",
 "hint"=>"Make sure you've typed all of your code exactly as above and kept all the capitalizations and symbols the same.  ",
 "solution"=>"paper = makeWorkspace()\r\nface = paper.ellipse(200,200,60,80)",
 "image_url"=>"step2.png",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>37,
 "kit_id"=>7,
 "description"=>"Now that we've changed the background when you select the correct answer we can see a way to add a new question. Simply add it to the function as well. \r\n<code>answer3.click(->\r\n&nbsp;&nbsp;alert(\"Correct!\")\r\n&nbsp;&nbsp;background = paper.rect(0,0,400,400)\r\n&nbsp;&nbsp;background.attr(\"fill\", \"yellow\")\r\n&nbsp;&nbsp;question = paper.text(200, 50, \"You new question here\")\r\n&nbsp;&nbsp;answer1 = paper.text(200, 80, \"your new answer1\")\r\n)</code>\r\n\r\nAdd as many answers as you like. ",
 "spec"=>"",
 "success_message"=>"Add some more answers, as many as you like. Try the quiz to make sure it works. ",
 "position"=>7,
 "created_at"=>"2012-03-01 16:53:52 UTC",
 "updated_at"=>"2012-03-27 20:08:10 UTC",
 "title"=>"Another question",
 "hint"=>"Double check that everything you want to be in the \"correctAnswer\" function is lined up under correctAnswer. ",
 "solution"=>"paper = makeWorkspace()\r\nbg = paper.rect(0,0,400, 400)\r\nbg.attr(\"fill\", \"yellow\")\r\nquestion = paper.text(200, 50, \"How cold is it today?\")\r\n\r\nanswer1 = paper.text(200, 80, \"a little nippy out there\") \r\nanswer2 = paper.text(200, 120, \"spring-like\") \r\nanswer3 = paper.text(200, 160, \"watch out for global warming\") \r\n\r\nanswer3.click( ->\r\n&nbsp;&nbsp;alert(\"Correct!\")\r\n&nbsp;&nbsp;background = paper.rect(0,0,400,400)\r\n&nbsp;&nbsp;background.attr(\"fill\", \"yellow\")\r\n&nbsp;&nbsp;question = paper.text(200, 50, \"How warm is it today?\")\r\n&nbsp;&nbsp;answer1 = paper.text(200, 80, \"sweltering\") \r\n&nbsp;&nbsp;answer2 = paper.text(200, 120, \"ouch, that burns!\") \r\n&nbsp;&nbsp;answer3 = paper.text(200, 160, \"rainy\") \r\n)",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>34,
 "kit_id"=>7,
 "description"=>"Try changing your code so it looks like this: \r\n\r\n<code>\r\nquestion2 = ->\r\n&nbsp;&nbsp;background = paper.rect(0,0,400,400)\r\n&nbsp;&nbsp;background.attr(\"fill\", \"yellow\")\r\n&nbsp;&nbsp;question = paper.text(200, 50, \"How warm is it today?\")\r\n&nbsp;&nbsp;answer1 = paper.text(200, 80, \"sweltering\") \r\n&nbsp;&nbsp;answer2 = paper.text(200, 120, \"ouch, that burns!\") \r\n&nbsp;&nbsp;answer3 = paper.text(200, 160, \"rainy\")\r\n&nbsp;&nbsp;answer2.click(->\r\n&nbsp;&nbsp;&nbsp;&nbsp;alert(\"Correct!\")\r\n&nbsp;&nbsp;)\r\n\r\nanswer3.click( ->\r\n&nbsp;&nbsp;alert(\"Correct!\")\r\n&nbsp;&nbsp;question2()\r\n)\r\n</code>\r\n",
 "spec"=>"",
 "success_message"=>"You didn't know it, but you've been using functions all along. Everytime you type a word followed by parentheses you are using a function that someone else wrote for you. ",
 "position"=>9,
 "created_at"=>"2012-02-29 22:47:42 UTC",
 "updated_at"=>"2012-03-27 20:08:28 UTC",
 "title"=>"Function",
 "hint"=>"Make sure your indentation is correct (that's the number of spaces at the start of each line). All the code that goes into a function should be indented.",
 "solution"=>"paper = makeWorkspace()\r\n\r\nbg = paper.rect(0,0,400, 400)\r\nbg.attr(\"fill\", \"yellow\")\r\nquestion = paper.text(200, 50, \"How cold is it today?\")\r\n\r\nanswer1 = paper.text(200, 80, \"a little nippy out there\") \r\nanswer2 = paper.text(200, 120, \"spring-like\") \r\nanswer3 = paper.text(200, 160, \"watch out for global warming\") \r\n\r\nquestion2 = ->\r\n&nbsp;&nbsp;background = paper.rect(0,0,400,400)\r\n&nbsp;&nbsp;background.attr(\"fill\", \"yellow\")\r\n&nbsp;&nbsp;question = paper.text(200, 50, \"How warm is it today?\")\r\n&nbsp;&nbsp;answer1 = paper.text(200, 80, \"sweltering\") \r\n&nbsp;&nbsp;answer2 = paper.text(200, 120, \"ouch, that burns!\") \r\n&nbsp;&nbsp;answer3 = paper.text(200, 160, \"rainy\")\r\n&nbsp;&nbsp;answer2.click(->\r\n&nbsp;&nbsp;&nbsp;&nbsp;alert(\"Correct!\")\r\n&nbsp;&nbsp;)\r\n\r\nanswer3.click( ->\r\n&nbsp;&nbsp;alert(\"Correct!\")\r\n&nbsp;&nbsp;question2()\r\n)",
 "image_url"=>"",
 "bonus"=>true,
 "freeplay"=>false,
 "more_info"=>"Now why did we do this? \r\n\r\nThink about writing a 3rd question, and fourth, and a fifth- do you see how your code is going to be pretty far indented by the time you're done? \r\n\r\nInstead of adding all our code to the end and indenting it each the way we can use a <code>function</code>. \r\n\r\nA function will let us write out our code and give it a nickname, then we can pick it back up and use it whenever we want. "},
{"id"=>51,
 "kit_id"=>10,
 "description"=>"We want to be able to start this game any time rather than automatically starting it. \r\n\r\nIn the code sample, a red line means you should remove it from your code. <code><num>38\r\n38\r\n39\r\n|\r\n40\r\n41\r\n|\r\n</num><delete>showMole()</delete><add>button = paper.rect(123, 170, 150, 60)\r\nbutton.attr(\"fill\":'deeppink', 'stroke':'white', 'stroke-width':'3', 'r':12)\r\ntext = paper.text(200, 200, \"Start\" )\r\ntext.attr('font-size':24, 'font-family':'monospace', 'fill': 'yellowgreen', 'font-weight':'bold')</add></code>\r\nGo to the last line of your code, delete showMole() and type in this example. ",
 "spec"=>nil,
 "success_message"=>"Removing showMole() means the mole doesn't appear. \r\nBut did you notice the button? Try changing the text.",
 "position"=>9,
 "created_at"=>"2012-03-26 14:25:50 UTC",
 "updated_at"=>"2012-03-28 16:29:20 UTC",
 "title"=>"Start button",
 "hint"=>"",
 "solution"=>"paper = makeWorkspace() \r\nbackground = paper.rect(0,0,400,400) \r\nbackground.attr('fill':'deepskyblue')\r\nmolehole = paper.circle(50,50,30).attr('fill':'navy', 'stroke-width': 0)\r\n_(4).times( (i) ->\r\n&nbsp;&nbsp;_(4).times( (j) ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveLeft = i * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveRight = j * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;molehole.clone().transform(\"T\" + moveLeft + \",\" + moveDown)\r\n&nbsp;&nbsp;)\r\n)\r\nmole = paper.image('http://localhost:5000/assets/mole.png', 6, 10, 80, 80)\r\n$('body').append($(\"&lt;div id='sound'&gt;\"))\r\nplaySound = (src) ->\r\n&nbsp;&nbsp;$(\"#sound\").html(\"&lt;embed src='\"+src+\"' hidden='true' autostart='true' loop='false'&gt;\")<br />\r\nmole.click(->\r\n&nbsp;&nbsp;playSound(\"http://localhost:5000/assets/punch.wav\")\r\n)\r\nmole.hide()\r\nrandom = ->\r\n&nbsp;&nbsp;Math.floor(Math.random() * 4) * 100\r\ncount = 0\r\nshowMole = ->\r\n&nbsp;&nbsp;mole.animate\r\n&nbsp;&nbsp;&nbsp;&nbsp;x:6 + random(), y:10 + random(), 1700, \r\n&nbsp;&nbsp;&nbsp;&nbsp;() ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.show()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setTimeout(( ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.hide()  \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count++\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if count < 15\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;showMole()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count = 0\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;), 900)\r\nbutton = paper.rect(123, 170, 150, 60)\r\nbutton.attr(\"fill\":'deeppink', 'stroke':'white', 'stroke-width':'3', 'r':12)\r\ntext = paper.text(200, 200, \"Start\" )\r\ntext.attr('font-size':24, 'font-family':'monospace', 'fill': 'yellowgreen', 'font-weight':'bold')",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""},
{"id"=>53,
 "kit_id"=>10,
 "description"=>"Let's keep score on our game. We will have to set a score counter that will get incremented each time the player successfully whacks a mole. \r\n\r\nChange your mole click code: <code><num>18\r\n19\r\n20\r\n21\r\n</num><add>score = 0</add>\r\nmole.click ->\r\n<add>&nbsp;&nbsp;score++</add>\r\n&nbsp;&nbsp;playSound(\"http://localhost:5000/assets/punch.wav\")</code>\r\n\r\nLastly we will display the score at the end of the game. Inside your showMole function add:\r\n<code><num>35\r\n36\r\n37\r\n38\r\n39\r\n40\r\n41\r\n</num>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if count < 15\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;showMole()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count = 0\r\n<add>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;button.show()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text.attr(\"text\":\"Score: \" + score)\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text.show()</add></code>\r\n\r\nMake sure that button.show() has the exact same indentation as count = 0.",
 "spec"=>nil,
 "success_message"=>"And now you have a score. Play the game and see how you do or\r\nclick next to view your game on its very own page!",
 "position"=>11,
 "created_at"=>"2012-03-26 14:54:16 UTC",
 "updated_at"=>"2012-03-28 16:34:27 UTC",
 "title"=>"Keep score",
 "hint"=>"",
 "solution"=>"paper = makeWorkspace() \r\nbackground = paper.rect(0,0,400,400) \r\nbackground.attr('fill':'deepskyblue')\r\nmolehole = paper.circle(50,50,30).attr('fill':'navy', 'stroke-width': 0)\r\n_(4).times( (i) ->\r\n&nbsp;&nbsp;_(4).times( (j) ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveLeft = i * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;moveRight = j * 100\r\n&nbsp;&nbsp;&nbsp;&nbsp;molehole.clone().transform(\"T\" + moveLeft + \",\" + moveDown)\r\n&nbsp;&nbsp;)\r\n)\r\nmole = paper.image('http://localhost:5000/assets/mole.png', 6, 10, 80, 80)\r\n$('body').append($(\"&lt;div id='sound'&gt;\"))\r\nplaySound = (src) ->\r\n&nbsp;&nbsp;$(\"#sound\").html(\"&lt;embed src='\"+src+\"' hidden='true' autostart='true' loop='false'&gt;\")<br />\r\nscore = 0\r\nmole.click(->\r\n&nbsp;&nbsp;playSound(\"http://localhost:5000/assets/punch.wav\")\r\n&nbsp;&nbsp;score++\r\n)\r\nmole.hide()\r\nrandom = ->\r\n&nbsp;&nbsp;Math.floor(Math.random() * 4) * 100\r\ncount = 0\r\nshowMole = ->\r\n&nbsp;&nbsp;mole.animate\r\n&nbsp;&nbsp;&nbsp;&nbsp;x:6 + random(), y:10 + random(), 1700, \r\n&nbsp;&nbsp;&nbsp;&nbsp;() ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.show()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setTimeout(( ->\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mole.hide()  \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count++\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if count < 15\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;showMole()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else \r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count = 0\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;button.show()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text.attr(\"text\":\"Score: \" + score)\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text.show()\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;), 900)\r\nbutton = paper.rect(123, 170, 150, 60)\r\nbutton.attr(\"fill\":'deeppink', 'stroke':'white', 'stroke-width':'3', 'r':12)\r\ntext = paper.text(200, 200, \"Start\" )\r\ntext.attr('font-size':24, 'font-family':'monospace', 'fill': 'yellowgreen', 'font-weight':'bold')\r\nbutton.click( () ->\r\n&nbsp;&nbsp;button.hide()\r\n&nbsp;&nbsp;text.hide()\r\n&nbsp;&nbsp;showMole()\r\n)\r\ntext.click( () ->\r\n&nbsp;&nbsp;button.hide()\r\n&nbsp;&nbsp;text.hide()\r\n&nbsp;&nbsp;showMole()\r\n)",
 "image_url"=>"",
 "bonus"=>false,
 "freeplay"=>false,
 "more_info"=>""}]
steps.each do |step|
  if ENV['host']
    if step['hint']
      hint = step['hint']
      step['hint'] = hint.gsub('localhost:5000', ENV['host'])
    end
    if step['success']
      solution = step['success']
      step['success'] = success.gsub('localhost:5000', ENV['host'])
    end
    if step['solution']
      solution = step['solution']
      step['solution'] = solution.gsub('localhost:5000', ENV['host'])
    end
    description = step['description']
    step['description'] = description.gsub('localhost:5000', ENV['host'])
  end
  if existing_step = Step.where(id: step['id']).first
    existing_step.update_attributes(step.reject{|k,v| k == 'id'})
  elsif existing_step = Step.where(position: step['position']).where(kit_id: step['kit_id']).first
    existing_step.update_attributes(step.reject{|k,v| k == 'id'})
  else
    new_step = Step.new(step)
    new_step.id = step['id']
    new_step.save
  end
end
